# NumPy  Tutorial
NumPy(Numerical Python)是Python语言的一个扩展程序，支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。  
NumPy是一个运行速度非常快的数学库，主要用于数组计算，包含：
- 一个强大的N维数组对象ndarray
- 广播功能函数
- 整合C/C++/Fortran代码的工具
- 线性代数、傅立叶变换、随机数生成等

In [ ]:
#如果你没有安装NumPy，运行下面这行代码
!pip install numpy

## NumPy Ndarray对象
NumPy最重要的一个特点是其N维数组对象ndarray，它是一系列同类型数据的集合，以0下标为开始进行集合中元素的索引。  
ndarray对象是用于存放同类型元素的多维数组。  
ndarray中的每个元素在内存中都有相同存储大小的区域。  
ndarray内部由以下内容组成：
- 一个指向数据（内存或内存映射文件中的一块数据）的指针。
- 数据类型或dtype，描述在数组中的固定大小值的格子。 
- 一个表示数组形状（shape）的元组，表示各维度大小的元组。 
- 一个跨度元组（stride），其中的整数指的是为了前进到当前维度下一个元素需要“跨过”的字节数


跨度可以时负数，这样会使数组在内存中向后移动，切片中`obj[::-1]`或`obj[:,::-1]`就是如此。  
创建一个ndarray只需要调用NumPy的array函数即可：
```python
numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
```

参数说明

|名称|描述|
|---|---|
|object|数组或嵌套的数列|
|dtype|数组元素的数据类型，可选|
|copy|对象是否需要复制，可选|
|order|创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）|
|subok|默认返回一个与基类类型一致的数组|
|ndmin|指定生成数组的最小维度|

In [1]:
#实例1
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
#实例2
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
#实例3
a = np.array([1, 2, 3, 4, 5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [5]:
#实例4 
a = np.array([1, 2, 3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


ndarray对象由计算机内存的连续一维部分组成，并结合索引模式，将每个元素映射到内存块中的每一个位置。

## NumPy数据类型
NumPy支持的数据类型比Python内置的类型多很多，基本和C语言齐平。

|名称|描述|
|--|--|
|bool_|布尔类型数据类型|
|int_|默认的整数类型|
|intc|与C的int类型一样，一般是int32或int64|
|intp|用于索引的整数类型|
|int8|字节(-128 to 127)|
|int16|整数(-32768 to 32767)|
|int32|整数（-2147483648 to 2147483647）|
|int64|整数（-9223372036854775808 to 9223372036854775807）|
|uint8|无符号整数（0 to 255）|
|uint16|无符号整数（0 to 65535）|
|uint32|无符号整数（0 to 4294967295）|
|uint64|无符号整数（0 to 18446744073709551615）|
|float_|float64 类型的简写|
|float16|半精度浮点数，包括：1 个符号位，5 个指数位，10 个尾数位|
|float32|单精度浮点数，包括：1 个符号位，8 个指数位，23 个尾数位|
|float64|双精度浮点数，包括：1 个符号位，11 个指数位，52 个尾数位|
|complex_|complex128 类型的简写，即 128 位复数|
|complex64|复数，表示双 32 位浮点数（实数部分和虚数部分）|
|complex128|复数，表示双 64 位浮点数（实数部分和虚数部分）|
numpy 的数值类型实际上是 dtype 对象的实例，并对应唯一的字符，包括 np.bool_，np.int32，np.float32，等等。

**数据类型对象(dtype)**
数据类型对象(numpy.dtype类的实例)用来描述与数组对应的内存区域是如何使用，它描述了数据的以下几个方面：
- 数据的类型（整数，浮点数或者Python对象）
- 数据的大小
- 数据的字节顺序（小端法或大端法）
- 在结构化类型的情况下，字段的名称、每个字段的数据类型和每个字段所取得的内存块的部分
- 如果数据结构是子数组，那么它的形状和数据类型是什么

字节顺序是通过对数据类型预先设定`<`或`>`来决定的。`<`意味着小端法（最小值存储在最小的地址、即低位组放在最前面）。`>`意味着大端法（最重要的字节存储在最小的地址、即高位组放在最前面）。

```python
numpy.dtype(object, align, copy)
```
- object - 要转换的数据类型对象
- align - 如果为true，填充字段使其类似C的结构体
- copy - 复制dtype对象，如果为false，则是对内置数据类型对象的引用


In [1]:
#实例1
import numpy as np
#使用标量类型
dt = np.dtype(np.int32)
print(dt)

int32


In [2]:
#实例2
dt = np.dtype('i4')
print(dt)

int32


In [3]:
#实例3
dt = np.dtype('<i4')
print(dt)

int32


In [6]:
#实例4
#展示结构化数据类型
import numpy as np
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [7]:
#实例5
#将数据类型应用ndarray对象
dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype = dt)
print(a)

[(10,) (20,) (30,)]


In [9]:
#实例6
#类型字段名可以用于存取实际的age列
import numpy as np
dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a['age'])

[10 20 30]


In [10]:
#实例7
import numpy as np
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('markd', 'f4')])
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


每个内建类型都有一个唯一定义它的字符代码，如下

|字符|对应类型|
|--|--|
|b|布尔型|
|i|(有符号) 整型|
|u|无符号整型 integer|
|f|浮点型|
|c|复数浮点型|
|m|timedelta（时间间隔）|
|M|datetime（日期时间）|
|O|(Python) 对象|
|S, a|(byte-)字符串|
|U|Unicode|
|V|原始数据 (void)|


## NumPy数组属性
 NumPy数组的维数称为秩(rank)，秩就是轴的数量， 即数组的维数，一维数组的秩为1，二维数组的秩为2，以此类推。在NumPy中，每一个线性的数组称为是一个轴(axis)，也就是维数(dimensions)。比如说，二维数组相当于是两个一个维数组，其中第一个一维数组中每个元素又是一个一维数组。所以一维数组就是NumPy中的轴(axis)，第一个轴相当于是底层数组，第二个轴是底层数组里的数组。而轴的数量———秩，就是数组的维数。

 很多时候可以声明axis。axis=0，表示沿着第0轴进行操作，即对每一列进行操作；axis=1，表示沿着第1轴进行操作，即对每一行进行操作。

 NumPy的数组中比较重要ndarray对象属性有：
|属性|说明|
|--|--|
|ndarray.ndim|秩，即轴的数量或维度的数量|
|ndarray.shape|数组的维度，对于矩阵，n 行 m 列|
|ndarray.size|数组元素的总个数，相当于 .shape 中 n*m 的值|
|ndarray.dtype|ndarray 对象的元素类型|
|ndarray.itemsize|ndarray 对象中每个元素的大小，以字节为单位|
|ndarray.flags|ndarray 对象的内存信息|
|ndarray.real|ndarray元素的实部|
|ndarray.imag|ndarray 元素的虚部|
|ndarray.data|包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。|





**ndarray.ndim**  
ndarray.ndim用于返回数组的维数，等于秩

In [12]:
import numpy as np
a = np.arange(24)
print(a.ndim)
#现在调整其大小
b = a.reshape(2, 4, 3)
print(b.ndim)

1
3


**ndarray.shape**  
ndarray.shape表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即ndim属性（秩）。

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

(2, 3)


In [15]:
#调整数组大小
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape = (3, 2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
#NumPy也提供了reshape函数来调整数组大小
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


**ndarray.itemsize**  
ndarray.itemsize以字节的形式返回数组中每一个元素的大小。  


In [17]:
x = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(x.itemsize)

y = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(y.itemsize)

1
8


**ndarray.flags**  
ndarray.flags返回ndarray对象的内存信息，包含以下属性：
|属性|描述|
|--|--|
|C_CONTIGUOUS(C)|数据在一个单一的C风格的连续段中|
|F_CONTIGUOUS (F)|数据是在一个单一的Fortran风格的连续段中|
|OWNDATA (O)|数组拥有它所使用的内存或从另一个对象中借用它|
|WRITEABLE (W)|数据区域可以被写入，将该值设置为 False，则数据为只读|
|ALIGNED (A)|数据和所有元素都适当地对齐到硬件上|
|UPDATEIFCOPY (U)|这个数组是其它数组的一个副本，当这个数组被释放时，原数组的内容将被更新|

In [18]:
x = np.array([1, 2, 3, 4, 5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



## NumPy创建数组  
ndarray数组除了可以使用底层ndarray构造器来创建外，也可以通过以下几种方式创建

**numpy.empty**  
```python
numpy.empty(shape, dtype=float, order='C')
```

参数说明：
|参数|描述|
|shape|数组形状|
|dtype|数据类型，可选|
|order|有“C”和“F”两个选项，分别代表，行优先和列优先，在计算机内存中的存储元素的顺序|

In [19]:
x = np.empty([3 ,2], dtype=int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


**numpy.zeros**  
创建指定大小的数组，数组元素以0来填充：
```python
numpy.zeros(shape, dtype=float, order='C')
```

参数说明：
|参数|描述|
|--|--|
|shape|数组形状|
|dtype|数据类型，可选|
|order|‘C’用于C的行数组，或者‘F’用于FORTRAN的列数组|

In [20]:
x = np.zeros(5)
print(x)

y = np.zeros((5,), dtype=np.int)
print(y)

z = np.zeros((2, 2), dtype=[('x', 'i4'), ('y', 'i4')])
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


**numpy.ones**  
创建指定形状的数组，数组元素以1来填充
```python
numpy.ones(shape, dtype=None, order='C')
```

参数说明：
|参数|描述|
|--|--|
|shape|数组形状|
|dtype|数据类型，可选|
|order|‘C’用于C的行数组，或者‘F’用于FORTRAN的列数组|

In [21]:
x = np.ones(5)
print(x)

x = np.ones([2, 2], dtype=int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


## NumPy从已有的数组创建数组
**numpy.asarray**  
numpy.asarray类似numpy.array，但numpy.asarray参数只有3个，比numpy.array少两个。
```python
numpy..asarray(a, dtype=None, order=None)
```

参数说明：
|参数|描述|
|--|--|
|a|任意形式的输入参数，可以是，列表，列表的元组，元组，元组的元组，元组的列表，多维数组|
|dtype|数据类型，可选|
|order|可选|



In [22]:
import numpy as np

x = [1, 2, 3]
a = np.asarray(x)
print(a)

[1 2 3]


In [23]:
x = (1, 2, 3)
a = np.asarray(x)
print(a)

[1 2 3]


In [24]:
x = [(1, 2, 3), (4, 5)]
a = np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


/Users/zhouyuchen/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [26]:
x = [1, 2, 3]
a = np.asarray(x, dtype=float)
print(a)


[1. 2. 3.]


**numpy.frombuffer**  
numpy.frombuffer 用于实现动态数组  
numpy.frombuffer 接受buffer输入参数，以流的形式读入转化成ndarray对象

```python
numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)
```

参数说明：
|参数|描述|
|--|--|
|buffer|可以是任意对象，会以流的形式读入|
|dtype|返回数组的数据类型|
|count|读取的数据数量，默认为-1，读取所有数据|
|offset|读取的起始位置，默认为0|

In [27]:
import numpy as np
s = b'Hello World'
a = np.frombuffer(s, dtype='S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


**numpy.fromiter**  
numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组。
```python
numpy.fromiter(iterable, dtype, count=-1)
```

|参数|描述|
|iterable|可迭代对象|
|dtype|返回数组的数据类型|
|count|读取的数据数量，默认为-1，读取所有数据|

In [28]:
import numpy as np

list = range(5)
it = iter(list)

x = np.fromiter(it ,dtype=float)
print(x)

[0. 1. 2. 3. 4.]
